language: elixir
elixir:
  - 1.4.1

otp_release:
  - 18.3
  - 19.0

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/test.travis.exs config/test.exs
  - psql -c 'create database travis_ci_test;' -U postgres
  - mix do ecto.create, ecto.migrate

script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
