language: elixir
elixir:
  - 1.4.1

otp_release:
  - 18.3
  - 19.0

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - cp config/test.travis.exs config/test.exs

script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
