language: elixir
elixir:
  - 1.3.2
  - 1.4.1

otp_release:
  - 18.3
  - 19.0

matrix:
  include:
    - elixir: 1.3.2
      otp_release: 18.3
    - elixir: 1.3.2
      otp_release: 19.0

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - cp config/test.travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
