version: "3"
services:
  web:
    build: .
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_HOSTNAME=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "4000:4000"
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: postgres:9.6
    ports:
      - "5432"
    networks:
      - webnet

networks:
  webnet:
